### ISSUE TITLE
Invocation of Event PlayerChatEvent threw an exception

### ISSUE THREAD

**Issue by ghost** [shoraii/hidenseek-amongus#2]
Hello,
My problem is that I get this Error Message whenever I type something in the Chat
![Error](https://user-images.githubusercontent.com/60573119/104822279-ae943880-5841-11eb-94fa-dcedbac20f6d.PNG)

**Comment by akulutka** [comment]
Fixed in the last commit, download the newest version [here](https://github.com/shoraii/hidenseek-amongus/releases/tag/0.1.1).
