### ISSUE TITLE
can u help me??

### ISSUE THREAD

**Issue by TrustyOrange** [shoraii/hidenseek-amongus#3]
its not working for me I did everything :(

**Comment by akulutka** [comment]
Hello. I hope this checklist will help you.

- Have you downloaded the [latest version](https://ci.appveyor.com/project/Impostor/Impostor/branch/dev/artifacts) of Impostor Server and followed the [instructions](https://github.com/Impostor/Impostor/blob/dev/docs/Running-the-server.md) on server installation?
- Did you check that your server has port 22023 opened?
- Have you and other players [patched their games](https://github.com/Impostor/Impostor#client)?
- Did you put HideNSeekAmongUs.dll in _plugins_ folder?

In case you have any problems with any step in the list, please describe them and attach logs and screenshots if possible.
